In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('H&M_dataset.csv')

In [3]:
df.head(3)

Unnamed: 0   productId          productName brandName  \
0           0   834333001          Derby Shoes       H&M   
1           1  1258600003  Pile-Lined Slippers       H&M   
2           2  1036812001          Derby Shoes       H&M   

                                                 url  price stockState  \
0  https://www2.hm.com/en_us/productpage.08343330...  49.99  Available   
1  https://www2.hm.com/en_us/productpage.12586000...  24.99  Available   
2  https://www2.hm.com/en_us/productpage.10368120...  56.99  Available   

   comingSoon colorName  isOnline  colors colorShades  newArrival  \
0       False     Black      True  272628    Charcoal       False   
1       False     Black      True  272628    Charcoal       False   
2       False     Black      True  272628    Charcoal       False   

          mainCatCode                                            details  \
0   men_shoes_dressed  Derby shoes with open lacing at front. Canvas ...   
1  men_shoes_slippers  Slippers in napped fabric. Decorative seam at ...   
2   men_shoes_dressed  Derby shoes in soft faux suede with open lacin...   

                                           materials  
0  COMPOSITION\nSole:Thermoplastic rubber 100%\nU...  
1  COMPOSITION\nLining:Polyester 100%\nUpper:Poly...  
2  COMPOSITION\nLining and insole:Cotton 100%\nUp...

In [4]:
df.shape

(9677, 16)

In [5]:
df.isnull().sum() #checking null values

Unnamed: 0        0
productId         0
productName       0
brandName         0
url               0
price             0
stockState        0
comingSoon        0
colorName         0
isOnline          0
colors            0
colorShades    3166
newArrival        0
mainCatCode       0
details           1
materials       159
dtype: int64

In [6]:
df['Unnamed: 0'].nunique() 

9677

In [7]:
df['productId'].nunique()

7671

In [8]:
df['productName'].nunique()

3246

In [9]:
df['brandName'].unique()

array(['H&M'], dtype=object)

In [10]:
df['url'].nunique()

7671

In [11]:
df['price'].nunique()

75

In [12]:
df['stockState'].nunique()

1

In [13]:
df['comingSoon'].unique()

array([False])

In [14]:
df['isOnline'].nunique()

1

In [15]:
df['colors'].nunique()

955

In [16]:
df['colorShades'].nunique()

73

In [17]:
df['newArrival'].unique()

array([False,  True])

In [18]:
df['mainCatCode'].unique()

array(['men_shoes_dressed', 'men_shoes_slippers', 'men_shoes_sneakers',
       'men_shoes_boots', 'men_shoes_loafers', 'men_shoes',
       'men_shoes_sneakers_hightop', 'ladies_premium_selection_shoes',
       'men_shoes_sandals_espandrillos', 'ladies_shoes_ankle_boots',
       'ladies_shoes_ballerinas_flats', 'ladies_nightwear_slippers',
       'ladies_shoes_sneakers', 'ladies_shoes_heels',
       'ladies_shoes_heels_pumps', 'ladies_shoes_pumps_highheels',
       'Ladies_shoes_loafers', 'ladies_shoes_sandals_espandrillos',
       'ladies_shoes_mules', 'ladies_trousers_culottes',
       'ladies_shoes_sandals', 'men_hoodiessweatshirts_sweatshirts',
       'men_cardigansjumpers_jumpers',
       'men_trousers_trousers_regular_all',
       'men_hoodiessweatshirts_hoodies', 'men_jacketscoats_jackets',
       'men_shirts_longsleeved', 'men_jeans_loose',
       'men_jacketscoats_coats', 'men_trousers_cargo',
       'men_trousers_casual', 'men_trousers_dressed',
       'men_trousers_chinos_sli

In [19]:
df['materials'].nunique()

4511

In [20]:
df['details'].nunique()

8239

In [21]:
df.duplicated().sum() #checking duplicate

0

# Data Cleaning

In [23]:
df.drop(columns=['colorShades'],inplace=True)

In [24]:
df = df.rename(columns={'Unnamed: 0': 'index'})

In [25]:
df.dropna(inplace=True)

# Modeling

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()
df1 = vect.fit_transform(df['colorName'])
df1=df1.toarray()

In [28]:
df2 = vect.fit_transform(df['colors'])
df2=df2.toarray()

In [29]:
df3 = vect.fit_transform(df['mainCatCode'])
df3=df3.toarray()

In [30]:
df4 = vect.fit_transform(df['details'])
df4=df4.toarray()

In [31]:
df5 = vect.fit_transform(df['materials'])
df5=df5.toarray()

In [32]:
df_mod = np.concatenate([df1,df2,df3,df4,df5,],axis=1)

- **cosine similerity**

In [34]:
from sklearn. metrics.pairwise import cosine_similarity
similarity = cosine_similarity(df_mod)
print(similarity)

[[1.         0.51394166 0.95777187 ... 0.06391613 0.18300812 0.07348886]
 [0.51394166 1.         0.51837323 ... 0.0646482  0.16947978 0.07666309]
 [0.95777187 0.51837323 1.         ... 0.06921335 0.18888145 0.09342122]
 ...
 [0.06391613 0.0646482  0.06921335 ... 1.         0.18348958 0.21866108]
 [0.18300812 0.16947978 0.18888145 ... 0.18348958 1.         0.14155766]
 [0.07348886 0.07666309 0.09342122 ... 0.21866108 0.14155766 1.        ]]


In [35]:
similarity.shape

(9517, 9517)

- **Creating a list**

In [37]:
list_of_item = df['productName'].tolist()

In [ ]:
Item_search = input("Search the Product:")

In [ ]:
import difflib
find_close_match = difflib.get_close_matches(Item_search, list_of_item)
print(find_close_match)

In [ ]:
close_match = find_close_match[0]
print(close_match)

In [ ]:
index_of_Item = df[df['productName'] == close_match]['index'].tolist()[0]
index_of_Item

In [ ]:
similarity_score = list(enumerate(similarity[index_of_Item]))
print(similarity_score)

In [ ]:
a=[]
for i in similarity_score:
    if (i[1] >= 0.75):
        a.append(i[0])

In [ ]:
a

In [ ]:
df0=pd.DataFrame({})
for item in a:
    df0[item] = df.loc[item][['productName','price','url']]

In [ ]:
df0.T